name: Deploy to Server

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub (optional, if pushing image)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env file
        run: |
          cat <<EOF > .env
          APP_NAME='hodos'
          PORT='3000'
          ENV='development'
          NODE_ENV='development'
          DB_HOST='103.75.184.206'
          DB_PORT='3306'
          DB_USERNAME='root'
          DB_PASSWORD='gennydev@123'
          DB_DATABASE='hodos_dev'
          DB_LOGGING='false'
          JWT_SECRET='hello'
          JWT_EXPIRY='24h'
          VIETMAP_API_KEY='9cbf0bc15d3901b7e043d8f76be8d73f370a82fe629a2d46'
          GITHUB_WEBHOOKS_TOKEN='secret'
          GEMINI_API_KEY='AIzaSyCeuHX33autYGQzsnwzn_aANlLYDVcWP5Y'
          PROJECT='HODOS_ADMIN'
          SOURCE='https://github.com/Tran-Huu-Tai-12-04-23/hodos-admin'
          TELEGRAM_BOT_TOKEN="7721080747:AAHFZYBw9nWpqvqTTYDr_0eErpAmCW66zfY"
          EMAIL_HOST='smtp.gmail.com'
          EMAIL_PORT='465'
          EMAIL_SECURE='true'
          EMAIL_USER="huutaidev@gmail.com"
          EMAIL_PASSWORD="vynpmzlehxevdqxg"
          FRONTEND_URL='http://localhost:3000'
          COMPANY_NAME='HODOS'
          COMPANY_ADDRESS='Tp Hồ Chí Minh, Việt Nam'
          LOGO_URL='https://firebasestorage.googleapis.com/v0/b/manager-project-3bc13.appspot.com/o/logo.png?alt=media&token=18e63389-a67a-4d7f-bd6a-1ade688c8088'
          VERIFICATION_CODE_EXPIRATION_MINUTES='10'
          FIREBASE_API_KEY=AIzaSyC4AF0EvsvapWk6Y09ZyC3Sm3ZsqzqpOHA
          FIREBASE_AUTH_DOMAIN=hodos-f29d9.firebaseapp.com
          FIREBASE_PROJECT_ID=hodos-f29d9
          FIREBASE_STORAGE_BUCKET=hodos-f29d9.appspot.com
          FIREBASE_MESSAGING_SENDER_ID=646639558632
          FIREBASE_APP_ID=1:646639558632:web:2e89d12a833252cb4c8e5d
          FIREBASE_MEASUREMENT_ID=G-W9YN4Y4290
          FIREBASE_SERVICE_ACCOUNT_JSON=${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          GOONG_API="https://rsapi.goong.io/trip"
          GOONG_API_KEY="Q8xgJs3mYDyoJSbtRkXLDhayucb8WkWsMVZWUYuW"
          EOF

      - name: Build Docker image
        run: docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }} .

      - name: Add tag docker image (optional)
        run: docker tag ${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Push Docker image to docker hub (optional)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Deploy to Server (using SSH and Docker)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TAG_NAME: ${{ secrets.TAG_NAME }}
        run: |
          sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p 24700 $SSH_USERNAME@$SSH_HOST << 'EOF'
            mkdir -p /container && cd /container
            if docker ps -aq --filter name=${{ secrets.IMAGE_NAME }} | grep -q .; then
                docker stop ${{ secrets.IMAGE_NAME }} || true
                docker rm -f ${{ secrets.IMAGE_NAME }} || true
            fi
            if docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }} --quiet | grep -q .; then
                docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }} --quiet | xargs -r docker rmi -f
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}
            docker run -d -p 3006:3000 --name ${{ secrets.IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}
          EOF
