name: Deploy to Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub (optional, if pushing image)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env file
        run: |
          cat <<EOF > .env
          APP_NAME='hodos'

          PORT='3000'
          ENV='development'
          NODE_ENV='development'
          DB_HOST='103.75.184.206'
          DB_PORT='3307'
          DB_USERNAME='root'
          DB_PASSWORD='gennydev@123'
          DB_DATABASE='Hodos-pog'
          DB_LOGGING='false'
          
          VIETMAP_API_KEY='9cbf0bc15d3901b7e043d8f76be8d73f370a82fe629a2d46'
          GITHUB_WEBHOOKS_TOKEN='secret'
          GEMINI_API_KEY='AIzaSyAjU2N_DMD2nX3thZvzdobJghu27yYo8JI,AIzaSyD_gRuCbZgz1PMOs_8ckzHz4600Bjjigb4'
          PROJECT='HODOS_ADMIN'
          SOURCE='https://github.com/Tran-Huu-Tai-12-04-23/hodos-admin'
          EMAIL_HOST='smtp.gmail.com'
          EMAIL_PORT='465'
          EMAIL_SECURE='true'
          EMAIL_USER="huutaidev@gmail.com"
          EMAIL_PASSWORD="vynpmzlehxevdqxg"
          FRONTEND_URL='http://localhost:3000'
          COMPANY_NAME='HODOS'
          COMPANY_ADDRESS='Tp Hồ Chí Minh, Việt Nam'
          LOGO_URL='https://firebasestorage.googleapis.com/v0/b/hodos-f29d9.appspot.com/o/trip%2F1-removebg-preview.png?alt=media&token=2499d15d-a73e-460d-9e6b-781b7ca470eb'
          VERIFICATION_CODE_EXPIRATION_MINUTES='10'
          
          # firebase 
          FIREBASE_STORAGE_BUCKET=hodos-42e2a.appspot.com
          FIREBASE_PROJECT_ID=hodos-42e2a
          FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDPkxv9UZntTX4C\nNyoc54cSlb5R2uAZx7y7jROSxLNas0vqRZ/13t8tz/pdUpHz9caf8/T0GOkeWZML\nua8jeVLTDtEQA3m3P+35wpq4MqGG9+hgr8K0hZJfEoQ0pctLJUzSK4AnszHaTBDj\nE6+FQFe2+/Hnq++RbIVU8+g0f7+X4wJPEPlwcTwgrepQiTpGW8uBQsogq4s5AdNb\ni5yQnEdkbWsr2K+VJGTKvmtAyGxLbWjJSkKu2FHtbZE36KwBoJ6dxCo926VIvgAC\nET01k2juLTcetu3WVhQjafl94KYQ0GDartj0TyD6HEl6j5iyt/V7W2QxREINEsOQ\nEpKRaAMPAgMBAAECggEAFEr2dopuuPNVeVP5SwAbhWacR5ZVSE/tlIxTOIsAWcKj\njlCmNbxHJ0xo1ozG9gm2FFceQGrbB3uMU54gkCBBR57wM1eTo6WdV0h+JbnVbsN3\ntVQZfdp9F8xQnnEC8eLAot9b1QXAvu2mzPxUsXs72AjDenmlnxrz4f1CWzeN/IQo\nwuqlYVz/o69ZJap2Mcq24oHKYvr2UOZ8b9ViYV0vtDIfVip0xmDuwMnB4b3oOSvX\n0Gm57/7jwOzRvHn9EWsyKQZyVW75k5U65CYbpaHlX1sSXC4be5NgtNp0Da2RNdpr\nXmKFlpNh1oevGeEclK8B9tONPlH35pYsC82dK6EtOQKBgQD05wMpgbmAbzbEJYmE\nMdkPokNbn3f8HFprZnpYelyM3YiGMP5JvMfu+btlJ6b8gyAwH/LdkbF3xIMleQQ9\ntS0uY7osmWcmwVlrwpSwayu/Bt8M895UEbsnudNKYJUdFTYehrNddpedfTNIN8pP\nKIuYZg0OrCPAMFBJVoZ0nTHpgwKBgQDY+xOsh+UfmLukEdePjVeYD7espVkQ73ik\nzEd6Zcd/Vh1KngDCHGDj3gRlQQ4t2fWte8UFY8LudwweGUjRu8xwGRc979cbIqF+\nVjjAlZnZPd91CRB5GK3Fhpcq0Fq5EsrB1h/X/GthXmcU79AY11ho1kY4W2d1+SAw\ni97yjTrmhQKBgQDMjjhh7uzWjg4cf44BUPGQ0WOZn/VEKxqLIqmGRY4QSunBzCJZ\nzMjins0bjKc5uvyjtcvRreOhug4gupgEQtReLwZOQkOaZ10dWQWA5cNAZ6je1MMb\nTUQZxmjpcwqZpCH0FWaz5l51OSIgbBkbTS5sOLEnVDj4SmKFHzRnKvWJqQKBgFCW\nqE77RjE/E+ozKkHJ+E+k/s4jt3nfx4pFyQJ/zOHRhR2So6t0yNO5QR6uU+rZujLN\n9nYzAFJ7ase/Elm7i4nS99vsOZN9gEehFIEKz1JtdZJNZI3liZ0EiR7AtgFpJl9p\n/PfGa8eFPXn8O+kOCmsdsoT6Beo+NiNxv8OMiuTVAoGAFzsjQmOeVoDdvjmoDdVk\nJCnlQZVc3n2mDW8CMwkpUQyBnst7HI10d1v2yKIXe7TxDfcXHZBSzABQU3Eos4Ne\nIlgRGQ0nhtm82tND8qMzcPLXjz3xA3yHBPG6d8qV3fWZ7RmLxCrDetBUXDhXNCZd\npoKJAVglNX2cBIN+e36qo9U=\n-----END PRIVATE KEY-----\n"
          FIREBASE_CLIENT_EMAIL=firebase-adminsdk-5v0th@hodos-42e2a.iam.gserviceaccount.com
          FIREBASE_CLIENT_ID=109202614267557083246
          
          #map key
          GOONG_API="https://rsapi.goong.io/trip"
          GOONG_API_KEY="Q8xgJs3mYDyoJSbtRkXLDhayucb8WkWsMVZWUYuW"
          
          #jwt key
          JWT_SECRET="JWT_SECRET"
          JWT_EXPIRY='24h'
          
          BANK_NAME='TpBank'
          BANK_ACCOUNT="05677267222"
          SEPAY_API_KEY='WOHMIWF9JFGVJUCRZB9EPY68BNDAY3N7CTYS7JIGKKTYMWIXEKLTNXSVSD4ZVDPU'
          # để kiểm tra khi schedule
          KEY_SECRET=TAI_DEP_TRAI
          #cloure flare storage 
          CLOUDFLARE_ACCOUNT_ID='cb18f5d844d9284fb1ce5eef550ebe4a'
          CLOUDFLARE_ACCOUNT_API_TOKEN='NRWaKqsu9jwxEq38NlQWx44ALRfxEUuSg0RIHllA'
          CLOUDFLARE_ACCESS_KEY_ID='ece92a505c9ac1ad03c2470366551da9'
          CLOUDFLARE_SECRET_ACCESS_KEY='eb9b34d72742d20dce602c1c52a04488b3f7c5a04a69995c5f52f49ca2051216'
          CLOUDFLARE_BUCKET_NAME='hodos'
          CLOUDFLARE_ENDPOINT='https://cb18f5d844d9284fb1ce5eef550ebe4a.r2.cloudflarestorage.com'
          CLOUDFLARE_PUBLIC_IMG_ENDPOINT='https://pub-8522858fd58049a6b24d543265789c51.r2.dev/'
          EOF

      - name: Build Docker image
        run: docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }} .

      - name: Add tag docker image (optional)
        run: docker tag ${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Push Docker image to docker hub (optional)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Deploy to Server (using SSH and Docker)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TAG_NAME: ${{ secrets.TAG_NAME }}
        run: |
          sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p 24700 $SSH_USERNAME@$SSH_HOST << 'EOF'
            mkdir -p /container && cd /container
            if docker ps -aq --filter name=${{ secrets.IMAGE_NAME }} | grep -q .; then
                docker stop ${{ secrets.IMAGE_NAME }} || true
                docker rm -f ${{ secrets.IMAGE_NAME }} || true
            fi
            if docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }} --quiet | grep -q .; then
                docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }} --quiet | xargs -r docker rmi -f
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}
            docker run -d -p 3006:3000 --name ${{ secrets.IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}
          EOF
