name: Deploy to Server

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub (optional, if pushing image)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env file
        run: |
          cat <<EOF > .env
          APP_NAME='hodos'
          PORT='3000'
          ENV='development'
          NODE_ENV='development'
          DB_HOST='103.75.184.206'
          DB_PORT='3306'
          DB_USERNAME='root'
          DB_PASSWORD='gennydev@123'
          DB_DATABASE='hodos_dev'
          DB_LOGGING='false'
          JWT_SECRET='hello'
          JWT_EXPIRY='24h'
          VIETMAP_API_KEY='9cbf0bc15d3901b7e043d8f76be8d73f370a82fe629a2d46'
          GITHUB_WEBHOOKS_TOKEN='secret'
          GEMINI_API_KEY='AIzaSyCeuHX33autYGQzsnwzn_aANlLYDVcWP5Y'
          PROJECT='HODOS_ADMIN'
          SOURCE='https://github.com/Tran-Huu-Tai-12-04-23/hodos-admin'
          TELEGRAM_BOT_TOKEN="7721080747:AAHFZYBw9nWpqvqTTYDr_0eErpAmCW66zfY"
          EMAIL_HOST='smtp.gmail.com'
          EMAIL_PORT='465'
          EMAIL_SECURE='true'
          EMAIL_USER="huutaidev@gmail.com"
          EMAIL_PASSWORD="vynpmzlehxevdqxg"
          FRONTEND_URL='http://localhost:3000'
          COMPANY_NAME='HODOS'
          COMPANY_ADDRESS='Tp Hồ Chí Minh, Việt Nam'
          LOGO_URL='https://firebasestorage.googleapis.com/v0/b/manager-project-3bc13.appspot.com/o/logo.png?alt=media&token=18e63389-a67a-4d7f-bd6a-1ade688c8088'
          VERIFICATION_CODE_EXPIRATION_MINUTES='10'
          FIREBASE_API_KEY=AIzaSyC4AF0EvsvapWk6Y09ZyC3Sm3ZsqzqpOHA
          FIREBASE_AUTH_DOMAIN=hodos-f29d9.firebaseapp.com
          FIREBASE_PROJECT_ID=hodos-f29d9
          FIREBASE_STORAGE_BUCKET=hodos-f29d9.appspot.com
          FIREBASE_MESSAGING_SENDER_ID=646639558632
          FIREBASE_APP_ID=1:646639558632:web:2e89d12a833252cb4c8e5d
          FIREBASE_MEASUREMENT_ID=G-W9YN4Y4290
          FIREBASE_SERVICE_ACCOUNT_JSON={"type":"service_account","project_id":"hodos-f29d9","private_key_id":"c1bb520f12941d31ef0149b8e661ff22f30f9b79","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDsWYn/HSZuM9eG\nFGWAdYhRauE2ccKmFaQ54EGtyNh0Nd/BMYGCngF/6fetE8sxVxNUaaEkUtzhSNaL\nCGqKMaEMVyZ1ZwPt6Mz6b9M6GIF9HqKZIKAhtve8/xLKGArDZNFYSm12fs2KHfkx\nj2NNajqVUgRkXLmbKVKOd2Kg8GBMaF2PjXG5FfT/af1NaVUKTS5LZkPVFpMwMKhQ\nrVzIawIJfar6oxuMGm2WHTZE30K7ah9B71uMpTzQFxYU3GnIStPyLFiZRDYSpfXg\nRdEsQfT6e72l+K3S4PLcSBzmbWIe8YQGf74Ma4hJ/EzRjTBCgHvd3cpvfBoPP5Ws\naz7WaG8dAgMBAAECggEAWp3t2cEsZd48iOyzCfCGJmkrFfvB3Hm5sHL5246A5vVs\n5556gEDiZE+pJVPMeQtgnuGs5cdbZojNsRq19mwWyitz1Fl92S6DwJU1UDXrF7Sy\nNLGck7CaBX1qj89t+QJjfU1z8JWnaogZbdYDBcBv26ZJhs1CYGoUfAjr6LagxUoV\nzCglQioKMF3NyedUQyD1QL0aZ4leNwLo+oqIFkRV5Ze4EFBTFXTMXJl5oX+WCYaF\n5HGwMRfH+Y3P0g2T+PxlMCW3fg/wlBDmekSpD+RwXMa8m5uBvp9j6NxHy3YvwKVS\nL90GXtsQzQx0R8sHs4zVE9aM1MPW7DjrAySvFsAKxQKBgQD4VJt35EAl3a4N4CWg\ndVKw1SR4t0OdN/8h+5XGOFtkneT8LmUe7xPf3KYdPcmYrPmhsvjBKH6miRnEHTnI\nBl4S1QkpXqEnVHA4/7swnL2+E8ex9YzTMH+gGTCL0+j5v7HrRKAG8FDcWi/Dn6Sb\nZTdbHhH2KPTdtqIWKcRJroWKNwKBgQDzpjUnJ93IbHw/OV/iZ2yyR+g07NIokhXq\nKZKtFK/veiYuPgKi3gxVCxCFKnyPYefu5I8avBiOn11R9/zhCoheKPomYLIhMaCt\noj/Kim1rtwA9V9fynbkHSPaxV1Qso92RL4HmSFZL9ljvzvUGyI6tOmKMGUkfBhT2\nifsJ8hIXSwKBgQDBKf7s2W1UhwU24d4i3GAAESuXguZjSwV4R5yPXZMpxvAxgV1D\nHLEW9yl3oXJJAnQDZZW9mmQ54ndaZ2lkwB85AuFnfqZYU4QfsjzHaYTmb7hsIxbx\nx83emPl8KtAURRp+aRkZjKE5ZiW1Q17lSWwvwkoyclVWiRO3rbFzpv9VLQKBgQCF\nb91kWF0KSv+w0IdGw0WwTdlKQvjF51vBJouB5vaDvO30HVnsQJeYa7rcc2xMSl5v\nYxVMmv8H/RdqsNn5lX8hsmdtZT+pFjjdXyJ4ll9ewpaLAfTulpqi9r7EWQNsf0H1\nJYOKzssURxJmI33l/SjGjlcySxbUusv4SZEG3WAzCQKBgADX9PNz+uyLnlZCsStr\n7biNPMIlGICF2mCGLkAZQHyrzgtFsu08v5i39NmJK1ddqsf7e9PrjJcsS7gKe66V\nGUGP2kSf0ujgBJQdq43uGGpjqg4taVGzwQwKhjbwRWZXF4tv2UJCyo2mQ6q7vCC7\nTHDqnGNAEH1k/rynhFtaYYw7\n-----END PRIVATE KEY-----\n","client_email":"firebase-adminsdk-76yo0@hodos-f29d9.iam.gserviceaccount.com","client_id":"104897727190430685682","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-76yo0%40hodos-f29d9.iam.gserviceaccount.com","universe_domain":"googleapis.com"}
          GOONG_API="https://rsapi.goong.io/trip"
          GOONG_API_KEY="Q8xgJs3mYDyoJSbtRkXLDhayucb8WkWsMVZWUYuW"
          EOF

      - name: Build Docker image
        run: docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }} .

      - name: Add tag docker image (optional)
        run: docker tag ${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Push Docker image to docker hub (optional)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Deploy to Server (using SSH and Docker)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TAG_NAME: ${{ secrets.TAG_NAME }}
        run: |
          sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p 24700 $SSH_USERNAME@$SSH_HOST << 'EOF'
            mkdir -p /container && cd /container
            if docker ps -aq --filter name=${{ secrets.IMAGE_NAME }} | grep -q .; then
                docker stop ${{ secrets.IMAGE_NAME }} || true
                docker rm -f ${{ secrets.IMAGE_NAME }} || true
            fi
            if docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }} --quiet | grep -q .; then
                docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }} --quiet | xargs -r docker rmi -f
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}
            docker run -d -p 3006:3000 --name ${{ secrets.IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_NAME }}_${{ github.sha }}
          EOF
